### ISSUE TITLE
Update to manual, how to submit? 

### ISSUE THREAD

**Issue by sjparsons** [phpseclib/docs#2]
I have a comment on this page in the manual. 

    http://phpseclib.sourceforge.net/documentation/net.html#net_ssh_successive

My suggestion is that I've found the following command to be a helpful workaround.

    echo $ssh->exec('cd /; pwd');

What's the appropriate way to submit this suggestion? I'd be glad to create a pull request with my addition if you point me in the right direction. 

Cheers

**Comment by terrafrost** [comment]
So I apparently completely forgot about this.

Anyway, this has been done:

https://github.com/phpseclib/docs/commit/dd1c00d1a97d57b56ee7e06c6079b2a514734642
http://phpseclib.sourceforge.net/ssh/examples.html#chdir,
