### ISSUE TITLE
Hidden text visible when Key Derivation is activated

### ISSUE THREAD

**Issue by Joey3000** [phpseclib/docs#5]
On http://phpseclib.sourceforge.net/crypt/examples.html, when one activates the key derivation, a text which should be hidden appears (part of the example key string; its length depends on the selected key length):

![doc_issue](https://cloud.githubusercontent.com/assets/3662335/12409858/86ed51a8-be6e-11e5-82de-c54122638ee0.png)

**Comment by terrafrost** [comment]
Nice find! The latest commit fixes it:

https://github.com/phpseclib/docs/commit/bc22d9bac1831174efc7e05837ce441717548709
http://phpseclib.sourceforge.net/crypt/examples.html#aes,cbc,outer,k128,kr128,b128,pbkdf2,padding,

Thanks!
